# Vector_Windows_EZTools_RECmd_BamDam config.
# Description: Process Windows artefacts parsed with RECmd (CSV output).
#              Provides full path of the executable file that was run on the system and last execution date/time.
#              Filename should match: "*_BamDam_*.csv"
#              Hive type: SYSTEM
#              Registry key path: "ControlSet00*\Services\bam\State\UserSettings\*" and "ControlSet00*\Services\bam\UserSettings\*" and "ControlSet00*\Services\dam\State\UserSettings\*" and "ControlSet00*\Services\dam\UserSettings\*"
#              RECmd command: RECmd\RECmd.exe -d %sourceDirectory% --bn RECmd\RECmd_Batch_MC.reb --nl --csv %destinationDirectory% -q
#              Example command: RECmd\RECmd.exe -d "C:\" --bn RECmd\RECmd_Batch_MC.reb --nl --csv <YOUR_OUTPUT> -q
#              source = "windows_registry_bamdam" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.RECmd_BamDam_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the RECmd Registry BamDam files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*_BamDam_*.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.RECmd_BamDam_csv_parser]
  type = "remap"
  inputs = ["RECmd_BamDam_csv_input"]
  source = '''
    # Expect CSV header:
    # BatchKeyPath,BatchValueName,Program,ExecutionTime
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[Registry_BamDam] Unable to split CSV: " + err, level: "error")
    }

    if fields[2] == "Program" {
      expected_header = "BatchKeyPath,BatchValueName,Program,ExecutionTime"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .batchkeypath = fields[0]
    .batchvaluename = fields[1]
    .program = fields[2]
    .executiontime = fields[3]

    .timestamp = .executiontime

    # Parse BatchKeyPath field to extract user SID. Expected format: S-1-5-1234567890-123456789-1234567890-512.
    .user_sid = parse_regex!(fields[0], r'UserSettings\\(?P<sid>.*)')."sid"

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_registry_bamdam"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''

[transforms.RECmd_BamDam_coerce_to_sink]
  type = "remap"
  inputs = ["RECmd_BamDam_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S.%f"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
