# Vector_Windows_EZTools_AmcacheParser_AmCache-DriveBinaries config.
# Description: Process Windows artefacts parsed with AmcacheParser (CSV output).
#              Filename should match: "*Amcache_DriveBinaries.csv"
#              AmcacheParser command: AmcacheParser.exe -f %sourceFile% --csv %destinationDirectory% -i
#              Example command: AmcacheParser.exe -f "C:\Windows\appcompat\Programs\Amcache.hve" --csv <YOUR_OUTPUT>
#              source = "windows_amcache-drivebinaries" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.AmcacheParser_AmCache-DriveBinaries_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the AmcacheParser AmCache DriveBinaries files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*Amcache_DriveBinaries.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.AmcacheParser_AmCache-DriveBinaries_csv_parser_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-DriveBinaries_csv_input"]
  source = '''
    # Expect CSV header:
    # KeyName,KeyLastWriteTimestamp,DriverTimeStamp,DriverLastWriteTime,DriverName,DriverInBox,DriverIsKernelMode,DriverSigned,DriverCheckSum,DriverCompany,DriverId,DriverPackageStrongName,DriverType,DriverVersion,ImageSize,Inf,Product,ProductVersion,Service,WdfVersion
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[AmCache-DriveBinaries] Unable to split CSV: " + err, level: "error")
    }

    if fields[1] == "KeyLastWriteTimestamp" {
      expected_header = "KeyName,KeyLastWriteTimestamp,DriverTimeStamp,DriverLastWriteTime,DriverName,DriverInBox,DriverIsKernelMode,DriverSigned,DriverCheckSum,DriverCompany,DriverId,DriverPackageStrongName,DriverType,DriverVersion,ImageSize,Inf,Product,ProductVersion,Service,WdfVersion"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .keyname = fields[0]

    if (fields[1] != null && fields[1] != "" && fields[1] != "\r") {
        # Parse KeyLastWriteTimestamp field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .keylastwritetimestamp, err = parse_timestamp(fields[1], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[Amcache_DriveBinaries] Unable to parse KeyLastWriteTimestamp timestamp: " + err, level: "error")
        }
    }

    if (fields[2] != null && fields[2] != "" && fields[2] != "\r") {
        # Parse DriverTimeStamp field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .drivertimestamp, err = parse_timestamp(fields[2], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[Amcache_DriveBinaries] Unable to parse DriverTimeStamp timestamp: " + err, level: "error")
        }
    }

    if (fields[3] != null && fields[3] != "" && fields[3] != "\r") {
        # Parse DriverLastWriteTime field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .driverlastwritetime, err = parse_timestamp(fields[3], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[Amcache_DriveBinaries] Unable to parse DriverLastWriteTime timestamp: " + err, level: "error")
        }
    }

    .drivername = fields[4]
    .driverinbox = to_bool!(fields[5])
    .driveriskernelmode = to_bool!(fields[6])
    .driversigned = to_bool!(fields[7])
    .driverchecksum = to_int!(fields[8])
    .drivercompany = fields[9]
    .driverid = fields[10]
    .driverpackagestrongname = fields[11]
    .drivertype = fields[12]
    .driverversion = fields[13]
    .imagesize = to_int!(fields[14])
    .inf = fields[15]
    .product = fields[16]
    .productversion = fields[17]
    .service = fields[18]
    .wdfversion = fields[19]
    .timestamp = .driverlastwritetime

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_amcache-drivebinaries"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''
