# Vector_Windows_EZTools_RECmd_TypedPaths config.
# Description: Process Windows artefacts parsed with RECmd (CSV output).
#              Filename should match: "*_TypedPaths_*.csv"
#              Hive type: NTUSER
#              Registry key path: Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths
#              RECmd command: RECmd\RECmd.exe -d %sourceDirectory% --bn RECmd\RECmd_Batch_MC.reb --nl --csv %destinationDirectory% -q
#              Example command: RECmd\RECmd.exe -d "C:\" --bn RECmd\RECmd_Batch_MC.reb --nl --csv <YOUR_OUTPUT> -q
#              source = "windows_registry_explorer_typedpaths" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.RECmd_TypedPaths_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the RECmd Registry TypedPaths files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*_TypedPaths_*.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.RECmd_TypedPaths_csv_parser_to_sink]
  type = "remap"
  inputs = ["RECmd_TypedPaths_csv_input"]
  source = '''
    # Expect CSV header:
    # HivePath,HiveType,Description,Category,KeyPath,ValueName,ValueType,ValueData,ValueData2,ValueData3,Comment,Recursive,Deleted,LastWriteTimestamp,PluginDetailFile
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[TypedPaths] Unable to split CSV: " + err, level: "error")
    }

    if fields[7] == "ValueData" {
      expected_header = "HivePath,HiveType,Description,Category,KeyPath,ValueName,ValueType,ValueData,ValueData2,ValueData3,Comment,Recursive,Deleted,LastWriteTimestamp,PluginDetailFile"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .category = fields[3]
    .valuename = fields[5]
    .valuetype = fields[6]
    .valuedata = fields[7]
    .deleted = to_bool!(fields[12])

    if (fields[13] != null && fields[13] != "" && fields[13] != "\r") {
      # Parse LastWriteTimestamp field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
      .lastwritetimestamp, err = parse_timestamp(fields[13], format: "%Y-%m-%d %H:%M:%S.%f")
      if err != null {
        log("[TypedPaths] Unable to parse LastWriteTimestamp timestamp: " + err, level: "error")
      }
    }

    .timestamp = .lastwritetimestamp

    if (fields[0] != null && fields[0] != "" && fields[0] != "\r") {
        if ((parse_regex!(fields[0], r'\\[a-zA-Z]\\Users\\(?P<user>.*)\\NTUSER.DAT$')."user") != null) {
          # Parse HivePath field to extract username. Expected format: "username".
          .user = parse_regex!(fields[0], r'\\[a-zA-Z]\\Users\\(?P<user>.*)\\NTUSER.DAT$')."user"
        } else if ((parse_regex!(fields[0], r'\\[a-zA-Z]\\Utilisateurs\\(?P<user>.*)\\NTUSER.DAT$')."user") != null) {
          # Parse HivePath field to extract username. Expected format: "username".
          .user = parse_regex!(fields[0], r'\\[a-zA-Z]\\Utilisateurs\\(?P<user>.*)\\NTUSER.DAT$')."user"
        }
    } else {
        .user = ""
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_registry_explorer_typedpaths"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''
