# Vector_Windows_EZTools_RecentFileCacheParser_RecentFileCache config.
# Description: Process Windows artefacts parsed with RecentFileCacheParser (CSV output).
#              Filename should match: "*_RecentFileCacheParser_*.csv"
#              WxTCmd command: RecentFileCacheParser.exe -f %sourceFile% --csv %destinationDirectory%
#              Example command: RecentFileCacheParser.exe -f "C:\Windows\AppCompat\Programs\RecentFileCache.bcf" --csv <YOUR_OUTPUT>
#              source = "windows_recentfilecacheparser" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.RecentFileCacheParser_RecentFileCache_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER}/**/*_RecentFileCacheParser_*.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.RecentFileCacheParser_RecentFileCache_csv_parser]
  type = "remap"
  inputs = ["RecentFileCacheParser_RecentFileCache_csv_input"]
  source = '''
    # Expect CSV header:
    # SourceFile,SourceCreated,SourceModified,SourceAccessed,Filename
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[RecentFileCacheParser] Unable to split CSV: " + err, level: "error")
    }

    if fields[0] == "SourceFile" {
      expected_header = "SourceFile,SourceCreated,SourceModified,SourceAccessed,Filename"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .sourcefile = fields[0]
    .sourcecreated = fields[1]
    .sourcemodified = fields[2]
    .sourceaccessed = fields[3]
    .filename = fields[4]

    if (.filename != null && .filename != "") {
      .filename = string!(.filename)
      if (contains(.filename, "users")) {
        # Parse Filename field to extract username. Expected format: "username".
        .user = parse_regex!(.filename, r'[a-zA-Z]:\\users\\(?P<user>[\w]+)\\*')."user"
      } else if (contains(.filename, "utilisateurs")) {
        # Parse Filename field to extract username. Expected format: "username".
        .user = parse_regex!(.filename, r'[a-zA-Z]:\\utilisateurs\\(?P<user>[\w]+)\\*')."user"
      }
    } else {
        .user = ""
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_recentfilecacheparser"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''

[transforms.RecentFileCacheParser_RecentFileCache_coerce]
  type = "remap"
  inputs = ["RecentFileCacheParser_RecentFileCache_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S.%f"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''

[transforms.RecentFileCacheParser_RecentFileCache_dedup_SourceCreated_to_sink]
  type = "remap"
  inputs = ["RecentFileCacheParser_RecentFileCache_coerce"]
  source = '''
    if !exists(.sourcecreated){
      abort
    }

    .timestamp = .sourcecreated
    .operation = "creation"
    .suboperation = "file_creation_sourcecreated"
  '''

[transforms.RecentFileCacheParser_RecentFileCache_dedup_SourceModified_to_sink]
  type = "remap"
  inputs = ["RecentFileCacheParser_RecentFileCache_coerce"]
  source = '''
    if !exists(.sourcemodified){
      abort
    }

    .timestamp = .sourcemodified
    .operation = "modification"
    .suboperation = "file_modification_sourcemodified"
  '''

[transforms.RecentFileCacheParser_RecentFileCache_dedup_SourceAccessed_to_sink]
  type = "remap"
  inputs = ["RecentFileCacheParser_RecentFileCache_coerce"]
  source = '''
    if !exists(.sourceaccessed){
      abort
    }

    .timestamp = .sourceaccessed
    .operation = "access"
    .suboperation = "file_access_sourceaccessed"
  '''
