# Vector_Windows_EZTools_AppCompatCacheParser_ShimCache config.
# Description: Process Windows artefacts parsed with AppCompatCacheParser (CSV output).
#              Filename should match: "*AppCompatCache.csv"
#              AppCompatCacheParser command: AppCompatCacheParser.exe -f %sourceFile% --csv %destinationDirectory%
#              Example command: AppCompatCacheParser.exe -f "C:\Windows\System32\config\SYSTEM" --csv <YOUR_OUTPUT>
#              source = "windows_shimcache" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.AppCompatCacheParser_ShimCache_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the AppCompatCacheParser ShimCache files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*AppCompatCache.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.AppCompatCacheParser_ShimCache_csv_parser_to_sink]
  type = "remap"
  inputs = ["AppCompatCacheParser_ShimCache_csv_input"]
  source = '''
    # Expect CSV header:
    # ControlSet,CacheEntryPosition,Path,LastModifiedTimeUTC,Executed,Duplicate,SourceFile
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[ShimCache] Unable to split CSV: " + err, level: "error")
    }

    if fields[0] == "ControlSet"{
      abort
    }

    .controlset = to_int!(fields[0])
    .cacheentryposition = to_int!(fields[1])
    .path = fields[2]

    if (fields[3] != null && fields[3] != "" && fields[3] != "\r") {
        # Parse LastModifiedTimeUTC field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .lastmodifiedtimeutc, err = parse_timestamp(fields[3], format: "%Y-%m-%d %H:%M:%S")
        if err != null {
          log("[Amcache_ProgramEntries] Unable to parse LastModifiedTimeUTC timestamp: " + err, level: "error")
        }
    }

    .executed = fields[4]
    .duplicate = to_bool!(fields[5])
    .sourcefile = fields[6]
    .timestamp = .lastmodifiedtimeutc

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_shimcache"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''
