# Vector_Windows_EZTools_RECmd_TypedURLs config.
# Description: Process Windows artefacts parsed with RECmd (CSV output).
#              Filename should match: "*_TypedURLs_*.csv"
#              Hive type: NTUSER
#              Registry key path: Software\Microsoft\Internet Explorer\TypedURLs
#              RECmd command: RECmd\RECmd.exe -d %sourceDirectory% --bn RECmd\RECmd_Batch_MC.reb --nl --csv %destinationDirectory% -q
#              Example command: RECmd\RECmd.exe -d "C:\" --bn RECmd\RECmd_Batch_MC.reb --nl --csv <YOUR_OUTPUT> -q
#              source = "windows_explorer_typedurls" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.RECmd_TypedURLs_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the RECmd Registry TypedURLs files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*_TypedURLs_*.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.RECmd_TypedURLs_csv_parser]
  type = "remap"
  inputs = ["RECmd_TypedURLs_csv_input"]
  source = '''
    # Expect CSV header:
    # BatchKeyPath,BatchValueName,Timestamp,Url,Slack
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[TypedURLs] Unable to split CSV: " + err, level: "error")
    }

    if fields[0] == "BatchKeyPath" {
      expected_header = "BatchKeyPath,BatchValueName,Timestamp,Url,Slack"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }


    .batchkeypath = fields[0]
    .batchvaluename = fields[1]
    .timestamp = fields[2]
    .url = fields[3]

    if (.file != null && .file != "") {
        if (contains!(.file, "_Windows_")) {
          # Parse File field to extract username. Expected format: "username".
          .user = "Windows_" + parse_regex!(.file, r'[a-zA-Z]_Users_(?P<kapeoutputfolder>.*)_Windows_(?P<user>.*)_NTUSER.DAT.csv')."user"
        } else if (contains!(.file, "_Users_")) {
          # Parse File field to extract username. Expected format: "username".
          .user = parse_regex!(.file, r'[a-zA-Z]_Users_(?P<kapeoutputfolder>.*)_Users_(?P<user>.*)_NTUSER.DAT.csv')."user"
        } else if (contains!(.file, "_Utilisateurs_")) {
          # Parse File field to extract username. Expected format: "username".
          .user = parse_regex!(.file, r'[a-zA-Z]_Utilisateurs_(?P<kapeoutputfolder>.*)_Utilisateurs_(?P<user>.*)_NTUSER.DAT.csv')."user"
        }
    } else {
        .user = ""
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_registry_explorer_typedurls"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''

[transforms.RECmd_TypedURLs_coerce_to_sink]
  type = "remap"
  inputs = ["RECmd_TypedURLs_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S.%f"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
