# Vector_Windows_EZTools_AmcacheParser_AmCache-Program-Entries config.
# Description: Process Windows artefacts parsed with AmcacheParser (CSV output).
#              Filename should match: "*Amcache_ProgramEntries.csv"
#              AmcacheParser command: AmcacheParser.exe -f %sourceFile% --csv %destinationDirectory% -i
#              Example command: AmcacheParser.exe -f "C:\Windows\appcompat\Programs\Amcache.hve" --csv <YOUR_OUTPUT>
#              source = "windows_amcache-programentries" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.AmcacheParser_AmCache-Program-Entries_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the AmcacheParser AmCache Program Entries files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*Amcache_ProgramEntries.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.AmcacheParser_AmCache-Program-Entries_csv_parser]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_input"]
  source = '''
    # Expect CSV header:
    # Old: ProgramId,KeyLastWriteTimestamp,Name,Version,Publisher,InstallDate,OSVersionAtInstallTime,BundleManifestPath,HiddenArp,InboxModernApp,Language,ManifestPath,MsiPackageCode,MsiProductCode,PackageFullName,ProgramInstanceId,RegistryKeyPath,RootDirPath,Type,Source,StoreAppType,UninstallString,InstallDateArpLastModified,InstallDateMsi,InstallDateFromLinkFile,Manufacturer
    # New: ProgramId,KeyLastWriteTimestamp,Name,Version,Publisher,InstallDateArpLastModified,InstallDate,InstallDateMsi,OSVersionAtInstallTime,InstallDateFromLinkFile,BundleManifestPath,HiddenArp,InboxModernApp,Language,ManifestPath,MsiPackageCode,MsiProductCode,PackageFullName,ProgramInstanceId,RegistryKeyPath,RootDirPath,Type,Source,StoreAppType,UninstallString,Manufacturer
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[AmCache-Program-Entries] Unable to split CSV: " + err, level: "error")
    }

    if fields[0] == "ProgramId" {
      expected_header = "ProgramId,KeyLastWriteTimestamp,Name,Version,Publisher,InstallDateArpLastModified,InstallDate,InstallDateMsi,OSVersionAtInstallTime,InstallDateFromLinkFile,BundleManifestPath,HiddenArp,InboxModernApp,Language,ManifestPath,MsiPackageCode,MsiProductCode,PackageFullName,ProgramInstanceId,RegistryKeyPath,RootDirPath,Type,Source,StoreAppType,UninstallString,Manufacturer"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .programid = fields[0]

    if (fields[1] != null && fields[1] != "" && fields[1] != "\r") {
        # Parse KeyLastWriteTimestamp field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .keylastwritetimestamp, err = parse_timestamp(fields[1], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[Amcache_ProgramEntries] Unable to parse KeyLastWriteTimestamp timestamp: " + err, level: "error")
        }
    }

    .name = fields[2]
    .version = fields[3]
    .publisher = fields[4]

    if (fields[5] != null && fields[5] != "" && fields[5] != "\r") {
        # Parse InstallDateMsi field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .installdate, err = parse_timestamp(fields[5], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[Amcache_ProgramEntries] Unable to parse InstallDateMsi timestamp: " + err, level: "error")
        }
    }

    .osversionatinstalltime = fields[6]
    .bundlemanifestpath = fields[7]
    if (is_boolean(fields[8])) {
      .hiddenarp = to_bool!(fields[8])
    } else {
      .hiddenarp = fields[8]
    }
    if (is_boolean(fields[9])) {
      .inboxmodernapp = to_bool!(fields[9])
    } else {
      .inboxmodernapp = fields[9]
    }
    .language = fields[10]
    .manifestpath = fields[11]
    .msipackagecode = fields[12]
    .msiproductcode = fields[13]
    .packagefullname = fields[14]
    .programinstanceid = fields[15]
    .registrykeypath = fields[16]
    .rootdirpath = fields[17]
    .type = fields[18]
    .source = fields[19]
    .storeapptype = fields[20]
    .uninstallstring = fields[21]

    if (fields[22] != null && fields[22] != "" && fields[22] != "\r") {
      # Parse InstallDateArpLastModified field to extract timestamp. Input format: MM/DD/YYYY hh:mm:ss. Expected format: YYYY-MM-DD hh:mm:ss.
      .installdatearplastmodified = parse_timestamp!(fields[22], format: "%m/%d/%Y %H:%M:%S")
    }

    if (fields[23] != null && fields[23] != "" && fields[23] != "\r") {
    # Parse InstallDateMsi field to extract timestamp. Input format: MM/DD/YYYY hh:mm:ss. Expected format: YYYY-MM-DD hh:mm:ss.
      .installdatemsi = parse_timestamp!(fields[23], format: "%m/%d/%Y %H:%M:%S")
    }

    if (fields[24] != null && fields[24] != "" && fields[24] != "\r") {
      # Parse InstallDateFromLinkFile field to extract timestamp. Input format: MM/DD/YYYY hh:mm:ss. Expected format: YYYY-MM-DD hh:mm:ss.
      .installdatefromlinkfile = parse_timestamp!(fields[24], format: "%m/%d/%Y %H:%M:%S")
    }

    .manufacturer = fields[25]
    .timestamp = .keylastwritetimestamp

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_amcache-programentries"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''

[transforms.AmcacheParser_AmCache-Program-Entries_dedup_KeyLastWriteTimestamp_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_parser"]
  source = '''
    if !exists(.keylastwritetimestamp){
      abort
    }

    .timestamp = .keylastwritetimestamp
    .operation = "program_modification_keylastwritetimestamp"
  '''

[transforms.AmcacheParser_AmCache-Program-Entries_dedup_InstallDate_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_parser"]
  source = '''
    if !exists(.installdate){
      abort
    }

    .timestamp = .installdate
    .operation = "creation"
    .suboperation = "program_installationdate"
  '''

[transforms.AmcacheParser_AmCache-Program-Entries_dedup_InstallDateArpLastModified_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_parser"]
  source = '''
    if !exists(.installdatearplastmodified){
      abort
    }

    .timestamp = .installdatearplastmodified
    .operation = "modification"
    .suboperation = "program_installdatearplastmodified"
  '''

[transforms.AmcacheParser_AmCache-Program-Entries_dedup_InstallDateMsi_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_parser"]
  source = '''
    if !exists(.installdatemsi){
      abort
    }

    .timestamp = .installdatemsi
    .operation = "creation"
    .suboperation = "program_installdatemsi"
  '''

[transforms.AmcacheParser_AmCache-Program-Entries_dedup_InstallDateFromLinkFile_to_sink]
  type = "remap"
  inputs = ["AmcacheParser_AmCache-Program-Entries_csv_parser"]
  source = '''
    if !exists(.installdatefromlinkfile){
      abort
    }

    .timestamp = .installdatefromlinkfile
    .operation = "creation"
    .suboperation = "program_installdatefromlinkfile"
  '''
