# Vector_Windows_EZTools_RECmd_RegistryServices config.
# Description: Process Windows artefacts parsed with RECmd (CSV output).
#              Filename should match: "*_Services_*.csv"
#              Hive type: SYSTEM
#              Registry key path: ControlSet00*\Services
#              RECmd command: RECmd\RECmd.exe -d %sourceDirectory% --bn RECmd\RECmd_Batch_MC.reb --nl --csv %destinationDirectory% -q
#              Example command: RECmd\RECmd.exe -d "C:\" --bn RECmd\RECmd_Batch_MC.reb --nl --csv <YOUR_OUTPUT> -q
#              source = "windows_registry_services" & sourcetype = "windows_artefact"
# Author(s): Jérôme BREBION, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.RECmd_RegistryServices_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the RECmd Registry Services files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*_Services_*.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.RECmd_RegistryServices_csv_parser_to_sink]
  type = "remap"
  inputs = ["RECmd_RegistryServices_csv_input"]
  source = '''
    # Expect CSV header:
    # BatchKeyPath,BatchValueName,Name,Description,DisplayName,StartMode,ServiceType,NameKeyLastWrite,ParametersKeyLastWrite,Group,ImagePath,ServiceDLL,RequiredPrivileges
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[RegistryServices] Unable to split CSV: " + err, level: "error")
    }

    if fields[0] == "BatchKeyPath" {
      expected_header = "BatchKeyPath,BatchValueName,Name,Description,DisplayName,StartMode,ServiceType,NameKeyLastWrite,ParametersKeyLastWrite,Group,ImagePath,ServiceDLL,RequiredPrivileges"
      if expected_header != .message {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header: " + string!(.message), level: "error")
      }
      abort
    }

    .batchkeypath = fields[0]
    .name = fields[2]
    .description = fields[3]
    .displayname = fields[4]
    .startmode = fields[5]
    .servicetype = fields[6]

    if (fields[7] != null && fields[7] != "" && fields[7] != "\r") {
        # Parse NameKeyLastWrite field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .namekeylastwrite, err = parse_timestamp(fields[7], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[RegistryServices] Unable to parse NameKeyLastWrite timestamp: " + err, level: "error")
        }
        .isnamekeylastwritenull = "false"
    } else {
        .isnamekeylastwritenull = "true"
    }

    if (fields[8] != null && fields[8] != "" && fields[8] != "\r") {
        # Parse ParametersKeyLastWrite field to extract timestamp. Input format: YYYY-MM-DD hh:mm:ss.zzz. Expected format: YYYY-MM-DD hh:mm:ss.
        .parameterskeylastwrite, err = parse_timestamp(fields[8], format: "%Y-%m-%d %H:%M:%S.%f")
        if err != null {
          log("[RegistryServices] Unable to parse ParametersKeyLastWrite timestamp: " + err, level: "error")
        }
    }

    .group = fields[9]
    .imagepath = fields[10]
    .servicedll = fields[11]
    .requiredprivileges = fields[12]

    .timestamp = .namekeylastwrite

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_registry_services"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''
