# Description: Process Zimbra access log files (Apache / NCSA combined format).
#              Filename should match: "*access_log*"
#              Default path on disk: /opt/zimbra/log/access_log*
#              source = "zimbra_access_logs" & sourcetype = "http_event"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.Zimbra_access_log_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the Zimbra access log files is required. Add '**' to process the specified folder recursively (exemple: \"C:\\logs\" or folder \"C:\\logs\\**\")}/*access_log*"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Zimbra_access_log_parser_to_sink]
  type = "remap"
  inputs = ["Zimbra_access_log_input"]
  source = '''
    ., err = parse_apache_log(.message, format: "combined")

    if (err != null) {
      log("Unable to convert to parse Zimbra log line: " + err, level: "error")
    }

    # Add the source host following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .source = "zimbra_access_logs"
    .sourcetype = "http_event"
  '''
