# Vector_Mailservers_Exchange_PowerShell_CmdletInfra_Cmdlet_logs config.
# Description: Process PowerShell CmdletInfra Cmdlet logs.
#              Filename should match: "CmdletInfra\*\Cmdlet\*.LOG"
#              Path %SystemDrive%/Program Files/Microsoft/Exchange Server/V15/Logging/CmdletInfra/(Powershell-Proxy|LocalPowerShell)/Cmdlet
#              https://m365internals.com/2022/10/07/hunting-in-on-premises-exchange-server-logs/
#              source = "exchange_powershell_cmdletinfra" & sourcetype = "exchange_artefacts"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.Exchange_PowerShell_CmdletInfra_Cmdlet_logs_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder matching the Exchange root install path is required.}/**/CmdletInfra/*/Cmdlet/*.LOG"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000
  offset_key = "__offset"

[transforms.Exchange_PowerShell_CmdletInfra_Cmdlet_logs_parser]
  type = "remap"
  inputs = ["Exchange_PowerShell_CmdletInfra_Cmdlet_logs_input"]
  source = '''
    # Expect CSV header:
    # DateTime,StartTime,RequestId,ClientRequestId,MajorVersion,MinorVersion,BuildVersion,RevisionVersion,ServerHostName,ProcessId,ProcessName,ThreadId,CultureInfo,Organization,AuthenticatedUser,ExecutingUserSid,EffectiveOrganization,UserServicePlan,IsAdmin,ClientApplication,Cmdlet,Parameters,CmdletUniqueId,UserBudgetOnStart,ContributeToFailFast,RunspaceSettingsCreationHint,ADViewEntireForest,ADRecipientViewRoot,ADConfigurationDomainControllers,ADPreferredGlobalCatalogs,ADPreferredDomainControllers,ADUserConfigurationDomainController,ADUserPreferredGlobalCatalog,ADuserPreferredDomainControllers,ThrottlingInfo,DelayInfo,ThrottlingDelay,IsOutputObjectRedacted,CmdletProxyStage,CmdletProxyRemoteServer,CmdletProxyRemoteServerVersion,CmdletProxyMethod,ProxiedObjectCount,CmdletProxyLatency,OutputObjectCount,ParameterBinding,BeginProcessing,ProcessRecord,EndProcessing,StopProcessing,BizLogic,PowerShellLatency,UserInteractionLatency,ProvisioningLayerLatency,ActivityContextLifeTime,TotalTime,ErrorType,ExecutionResult,CacheHitCount,CacheMissCount,GenericLatency,GenericInfo,GenericErrors,ObjectGuid,ExternalDirectoryOrganizationId,ExternalDirectoryObjectId,NonPiiParameters
    if .__offset == 0 || starts_with(string!(.message), "#") {
      if starts_with(string!(.message), "#Fields:") {
        expected_header = "#Fields: DateTime,StartTime,RequestId,ClientRequestId,MajorVersion,MinorVersion,BuildVersion,RevisionVersion,ServerHostName,ProcessId,ProcessName,ThreadId,CultureInfo,Organization,AuthenticatedUser,ExecutingUserSid,EffectiveOrganization,UserServicePlan,IsAdmin,ClientApplication,Cmdlet,Parameters,CmdletUniqueId,UserBudgetOnStart,ContributeToFailFast,RunspaceSettingsCreationHint,ADViewEntireForest,ADRecipientViewRoot,ADConfigurationDomainControllers,ADPreferredGlobalCatalogs,ADPreferredDomainControllers,ADUserConfigurationDomainController,ADUserPreferredGlobalCatalog,ADuserPreferredDomainControllers,ThrottlingInfo,DelayInfo,ThrottlingDelay,IsOutputObjectRedacted,CmdletProxyStage,CmdletProxyRemoteServer,CmdletProxyRemoteServerVersion,CmdletProxyMethod,ProxiedObjectCount,CmdletProxyLatency,OutputObjectCount,ParameterBinding,BeginProcessing,ProcessRecord,EndProcessing,StopProcessing,BizLogic,PowerShellLatency,UserInteractionLatency,ProvisioningLayerLatency,ActivityContextLifeTime,TotalTime,ErrorType,ExecutionResult,CacheHitCount,CacheMissCount,GenericLatency,GenericInfo,GenericErrors,ObjectGuid,ExternalDirectoryOrganizationId,ExternalDirectoryObjectId,NonPiiParameters"
        current_header = strip_whitespace(string!(.message))
        if expected_header != current_header {
          log("Unexpected CSV header!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
        }
      }
      abort
    }

    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    .datetime = fields[0]
    .starttime = fields[1]
    .requestid = fields[2]
    .clientrequestid = fields[3]
    .majorversion = fields[4]
    .minorversion = fields[5]
    .buildversion = fields[6]
    .revisionversion = fields[7]
    .serverhostname = fields[8]
    .processid = fields[9]
    .processname = fields[10]
    .threadid = fields[11]
    .cultureinfo = fields[12]
    .organization = fields[13]
    .authenticateduser = fields[14]
    .executingusersid = fields[15]
    .effectiveorganization = fields[16]
    .userserviceplan = fields[17]
    .isadmin = fields[18]
    .clientapplication = fields[19]
    .cmdlet = fields[20]
    .parameters = fields[21]
    .cmdletuniqueid = fields[22]
    .userbudgetonstart = fields[23]
    .contributetofailfast = fields[24]
    .runspacesettingscreationhint = fields[25]
    .adviewentireforest = fields[26]
    .adrecipientviewroot = fields[27]
    .adconfigurationdomaincontrollers = fields[28]
    .adpreferredglobalcatalogs = fields[29]
    .adpreferreddomaincontrollers = fields[30]
    .aduserconfigurationdomaincontroller = fields[31]
    .aduserpreferredglobalcatalog = fields[32]
    .aduserpreferreddomaincontrollers = fields[33]
    .throttlinginfo = fields[34]
    .delayinfo = fields[35]
    .throttlingdelay = fields[36]
    .isoutputobjectredacted = fields[37]
    .cmdletproxystage = fields[38]
    .cmdletproxyremoteserver = fields[39]
    .cmdletproxyremoteserverversion = fields[40]
    .cmdletproxymethod = fields[41]
    .proxiedobjectcount = fields[42]
    .cmdletproxylatency = fields[43]
    .outputobjectcount = fields[44]
    .parameterbinding = fields[45]
    .beginprocessing = fields[46]
    .processrecord = fields[47]
    .endprocessing = fields[48]
    .stopprocessing = fields[49]
    .bizlogic = fields[50]
    .powershelllatency = fields[51]
    .userinteractionlatency = fields[52]
    .provisioninglayerlatency = fields[53]
    .activitycontextlifetime = fields[54]
    .totaltime = fields[55]
    .errortype = fields[56]
    .executionresult = fields[57]
    .cachehitcount = fields[58]
    .cachemisscount = fields[59]
    .genericlatency = fields[60]
    .genericinfo = fields[61]
    .genericerrors = fields[62]
    .objectguid = fields[63]
    .externaldirectoryorganizationid = fields[64]
    .externaldirectoryobjectid = fields[65]
    .nonpiiparameters = fields[66]

    .timestamp = .datetime
    if is_nullish(.timestamp) {
      log("Timestamp is null for event, defaulting to current time: " + string!(.message), level: "warn")
      .timestamp = now()
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .serverhostname
    .source = "exchange_powershell_cmdletinfra"
    .sourcetype = "exchange_artefacts"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
    del(.__offset)
  '''

[transforms.Exchange_PowerShell_CmdletInfra_Cmdlet_logs_coerce_to_sink]
  type = "remap"
  inputs = ["Exchange_PowerShell_CmdletInfra_Cmdlet_logs_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9])|Z)?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? to_timestamp(value_string) ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
