# Description: Process Azure O365 Unified Audit logs, as retrieved by DFIR-ORC365RC.
#              Filename should match: "**/*UnifiedAuditLog*.json"
#              source = "o365_unifiedaudit" & sourcetype = "azure_artefact"
# Author(s): Axel ROC, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_TENANT = "<SOURCE_TENANT>"

data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.Azure_O365_UnifiedAuditLog_DFIR-O365RC_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The source folder containing the DFIR-O365RC JSON outputs is required}/**/*UnifiedAuditLog*.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Azure_O365_UnifiedAuditLog_DFIR-O365RC_parser]
  inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_input"]
  type = "remap"
  source = '''
    splitted, err = split(.message, "\n")
    if err != null {
      log("Unable to split message on newlines: " + err, level: "error")
    }

    . = map_values(splitted, true) -> |value| {
      is_value_json = value != null && is_json(value)
      if (err == null && is_value_json) {
        parsed_value, err = parse_json(value)
        if err != null {
          log("Unable to parse JSON: " + err, level: "error")
          null
        } else {
          parsed_value
        }
      }
    }
  '''

[transforms.Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich_to_sink]
  inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_parser"]
  type = "remap"
  source = '''
    if is_null(.CreationTime) == false {
      .CreationTime, err1 = to_timestamp(.CreationTime)
      if err1 != null {
        log("Unable to convert to timestamp: " + err1, level: "error")
      }
    }

    # Fields added to have the same nomenclature between the different log sources (audit, signins, unified logs...)
    .timestamp = .CreationTime
    .AccountName = .UserId

    # Flatten the .DeviceProperties, ExtendedProperties, Parameters, and ModifiedProperties fields.
    # Expected format:
    #   DeviceProperties": [
    #     {
    #       "Name": "OS",
    #       "Value": "MacOs"
    #     },
    #     {
    #       "Name": "BrowserType",
    #       "Value": "Other"
    #     },
    #     [...]
    DevicePropertiesArray = .DeviceProperties
    if is_null(.DeviceProperties) == false && is_array(.DeviceProperties) {
      DevicePropertiesMapped = {}
      for_each(array!(.DeviceProperties)) -> |_, item| {
        if exists(item.Name) && exists(item.Name) { DevicePropertiesMapped = set!(DevicePropertiesMapped, [item.Name], item.Value) }
      }
      .DeviceProperties = DevicePropertiesMapped
    }

    ExtendedPropertiesArray = .ExtendedProperties
    if is_null(.ExtendedProperties) == false && is_array(.ExtendedProperties) {
      ExtendedPropertiesMapped = {}
      for_each(array!(.ExtendedProperties)) -> |_, item| {
        if exists(item.Name) && exists(item.Name) { ExtendedPropertiesMapped = set!(ExtendedPropertiesMapped, [item.Name], item.Value) }
      }
      .ExtendedProperties = ExtendedPropertiesMapped
    }

    ParametersArray = .Parameters
    if is_null(.Parameters) == false && is_array(.Parameters) {
      ParametersMapped = {}
      for_each(array!(.Parameters)) -> |_, item| {
        if exists(item.Name) && exists(item.Name) { ParametersMapped = set!(ParametersMapped, [item.Name], item.Name) }
      }
      .Parameters = ParametersMapped
    }

    ModifiedPropertiesArray = .ModifiedProperties
    if is_null(.ModifiedProperties) == false && is_array(.ModifiedProperties) {
      ModifiedPropertiesMapped = {}
      for_each(array!(.ModifiedProperties)) -> |_, item| {
        if exists(item.Name) && exists(item.OldValue) { ModifiedPropertiesMapped = set!(ModifiedPropertiesMapped, [item.Name, "OldValue"], item.OldValue) }
        if exists(item.Name) && exists(item.NewValue) { ModifiedPropertiesMapped = set!(ModifiedPropertiesMapped, [item.Name, "NewValue"], item.NewValue) }
      }
      .ModifiedProperties = ModifiedPropertiesMapped
    }

    . = flatten(.)
    # Restore the original fields as well following the flattening, to keep both a flattened and array version.
    .DevicePropertiesArray = DevicePropertiesArray
    .ExtendedPropertiesArray = ExtendedPropertiesArray
    .ParametersArray = ParametersArray
    .ModifiedPropertiesArray = ModifiedPropertiesArray

    .host = "${SOURCE_TENANT:?The source AzureAD tenant is required}"
    .source = "o365_unifiedaudit"
    .sourcetype = "azure_artefact"
  '''
