# Description: Process AzureAD Sign Logs, as retrieved by DFIR-ORC365RC.
#              Filename should match: "**\*AADSigninLog*.json"
#              Logs should be converted from pretty-printed JSON to compacted JSON using the Onelifying_JSON.sh script (requiring jq).
#              source = "azure_aad_signins" & sourcetype = "azure_artefact"
# Author(s): Axel ROC, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_TENANT = "<SOURCE_TENANT>"

# Temporary folder used by Vector
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.AzureAD_DFIR-O365RC_signin_logs_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The source folder containing the DFIR-O365RC JSON outputs is required}\\**\\*AADSigninLog*.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  glob_minimum_cooldown_ms = 100000
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

# Double remap as events are stored as JSON objects in a single-line JSON array.
# The first remap "explode" the JSON array in multiple events.
[transforms.AzureAD_DFIR-O365RC_signin_logs_parser]
  inputs = ["AzureAD_DFIR-O365RC_signin_logs_input"]
  type = "remap"
  source = '''
    ., err = parse_json(.message)
    if err != null {
      log("Unable to parse JSON: " + err, level: "error")
    }
  '''

[transforms.AzureAD_DFIR-O365RC_signin_logs_enrich_to_sink]
  inputs = ["AzureAD_DFIR-O365RC_signin_logs_parser"]
  type = "remap"
  source = '''
    if is_null(.createdDateTime) == false {
      .createdDateTime, err1 = parse_timestamp(.createdDateTime, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(.createdDateTime, format: "%+")
      if err1 != null {
        log("Unable to convert to timestamp: " + err1, level: "error")
      }
    }

    if (.status.errorCode == 0 && .status.failureReason == "Other.") {
      .authenticationResult = "Success"
    } else {
      .authenticationResult = "Failure"
    }

    # Add new fields copied from existing ones to have the same nomenclature between the different log sources (audit, signins, unified logs...)
    .timestamp = .createdDateTime
    .ClientIP = .ipAddress
    .Username = .userDisplayName
    .AccountName = .userPrincipalName

    .host = "${SOURCE_TENANT:?The source AzureAD tenant is required}"
    .source = "azure_aad_signins"
    .sourcetype = "azure_artefact"

    . = flatten(.)
  '''
