# Description: Process VMware ESXi shell logs.
#              shell logs "contain a record of all commands typed into the ESXi Shell and shell events (for example, when the shell was enabled)."
#              Filename should match: "*shell.log*"
#              Default path on disk: /var/run/log/shell.log*
#              source = "vmware_esxi_shell" & sourcetype = "vmware_esxi_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.VMware_ESXi_shell_input]
  type = "file"
  ignore_checkpoints = true
  include = ["${INPUT_FOLDER:?The input folder containing the ESXi shell log files is required.}/**/*shell.log*"]
  read_from = "beginning"
  oldest_first = false
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.VMware_ESXi_shell_parser]
  type = "remap"
  inputs = ["VMware_ESXi_shell_input"]
  source = '''
    # Match main log entries
    # "2021-05-26T21:36:27Z shell[7537454]: Interactive shell session started"
    # "2021-05-26T21:36:40Z shell[7537454]: [root]: ping X.X.X.X"
    if (match_main, err = parse_regex(.message, r'^(?P<timestamp>.*?)\s(?P<terminal>.*?)\[(?P<session>.*?)\]:\s(?P<suffix>.*)$'); err == null) {
      .timestamp = parse_timestamp!(match_main.timestamp, format: "%Y-%m-%dT%H:%M:%SZ")
      .terminal = match_main.terminal
      .session = match_main.session
      # Match command execution log entries from suffix.
      #  "[root]: ping X.X.X.X"
      if (match_suffix_command, err = parse_regex(match_main.suffix, r'\[(?P<user>.*?)\]:\s(?P<command>.*)'); err == null) {
        .category = "execution"
        .suboperation = "esxi_execution"
        .user = match_suffix_command.user
        .command = match_suffix_command.command
      } else if (match_suffix_session_started, err = parse_regex(match_main.suffix, r'.*session started.*$'); err == null) {
        .operation = "login"
        .suboperation = "esxi_login"
        .message_suffix = match_main.suffix
      } else {
        .message_suffix = match_main.suffix
      }
    # Match other entries associated with a terminal type (such as enabling / disabling of terminal's login log entries).
    "2021-05-14T15:16:45Z SSH: SSH login enabled"
    "2021-05-14T15:10:26Z ESXShell: ESXi shell login disabled"
    } else if (match_other_terminal, err = parse_regex(.message, r'^(?P<timestamp>.*)\s(?P<terminal>.*):\s(?P<message>.*)$'); err == null) {
      .timestamp = parse_timestamp!(match_other_terminal.timestamp, format: "%Y-%m-%dT%H:%M:%SZ")
      .terminal = match_other_terminal.terminal
      .message_suffix = match_other_terminal.message
    # Match other log entries that have a timestamp.
    } else if (match_other, err = parse_regex(.message, r'^(?P<timestamp>.*)\s(?P<message>.*)$'); err == null) {
      .timestamp = parse_timestamp!(match_other.timestamp, format: "%Y-%m-%dT%H:%M:%SZ")
      .message_suffix = match_other.message
    } else {
      log("The following event is not in a valid format: " + to_string!(.message), level: "error")
    }

    # Delete irrelevant default fields
    del(.file)
    del(.message)
    del(.source_type)

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "vmware_esxi_shell"
    .sourcetype = "vmware_esxi_artefact"
  '''

[transforms.VMware_ESXi_shell_coerce_to_sink]
  type = "remap"
  inputs = ["VMware_ESXi_shell_parser"]
  source = '''
    . = map_values(.) -> |value| {
      value_string, convert_err = string(value)
      # Only coerce string (and not already casted types, such as int, timestamps, etc.).
      if convert_err != null {
        value
      # Matches a timestamp in various format ("T" or space separated, with or without post second precision, and with or without a timezone identifier).
      } else if (match(value_string, r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[0-1])[T|\s]([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{1,9})?(\s?[\+|\-]([01][0-9]|2[0-4]):?([0-5][0-9]))?$')) {
        tmp_value = parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f%z") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f %z") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S") ?? parse_timestamp(value_string, format: "%Y-%m-%dT%H:%M:%S%.f") ?? parse_timestamp(value_string, format: "%Y-%m-%d %H:%M:%S%.f") ?? value_string
        if is_string(tmp_value) {
          log("Failed to convert timestamp: " + value_string, level: "warn")
          value
        } else {
          tmp_value
        }
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_float(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
