# Description: Process FortiGate Traffic exported log files.
#              source = "fortigate_traffic" & sourcetype = "network_event"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.FortiGate_traffic_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the FortiGate traffic log files is required. Add '**' to process the specified folder recursively (exemple: \"C:\\logs\" or folder \"C:\\logs\\**\")}/*traffic*.log*"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  max_line_bytes = 100_000_000

[transforms.FortiGate_traffic_parser_to_sink]
  inputs = ["FortiGate_traffic_input"]
  type = "remap"
  source = '''
    ., err = parse_key_value(.message, key_value_delimiter: "=", field_delimiter: " ")
    if (err != null) {
      log("Unable to convert to parse log line: " + err, level: "error")
    }

    # Parse the date, time, and eventual timezone of the event.
    # Expected formats:
    # date=2017-11-15 time=11:44:16
    # date=2017-11-15 time=11:44:16 tz="+0200"

    # If a timezone ("tz" field) is not specified, the environnement variable UTC_OFFSET is used.
    timezone = ""
    if (exists(.tz)) {
      match_tz, err = parse_regex(.tz, r'^(?P<sign>[\-+])(?P<hours>\d{2})(?P<minutes>\d{2})$')
      if (err == null && match_tz.sign != null && match_tz.hours != null && match_tz.minutes != null) {
        timezone = to_string(match_tz.sign) + to_string(match_tz.hours) + ":" + to_string(match_tz.minutes)
      } else {
        log("Parsing of the timezone failed, using the specified UTC_OFFSET instead: " + err, level: "error")
      }
    }
    if (timezone == "") {
      timezone = "${UTC_OFFSET:?"The offset to UTC of the Fortigate timezone is required and will be used (only) if events do not specify a valid "tz" field. Expected format [+ | -]HH:MM."}"
    }

    new_timestamp, err = to_timestamp(to_string!(.date) + "T" + to_string!(.time) + timezone)
    if (err == null) {
      .timestamp = new_timestamp
    } else {
      log("Parsing of the timestamp failed: " + err, level: "error")
      abort
    }

    # Coerce types.
    . = map_values(.) -> |value| {
      if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S.%f %z"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else {
        value
      }
    }

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    if (exists(.srcname) && .srcname != "") {
      .host = .srcname
    } else if (exists(.srcip) && .srcip != "") {
      .host = .srcip
    } else {
      .host = .sourcehost
    }
    .source = "fortigate_traffic"
    .sourcetype = "network_event"
  '''
