# Description: Process Azure Netflow logs (CSV output).
#              Filename should match: "PT1H.json" and must be present in the default folder "insights-logs-networksecuritygroupflowevent".
#              Reference: https://learn.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview
#              source = "azure_nsg_flow" & sourcetype = "azure_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-12-16
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

# Set the default timezone to UTC+0 for timestamps that do not include a timezone.
timezone = "Etc/UTC"

[sources.Azure_NSG_flow_logs_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the Azure NSG flows JSON files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/insights-logs-networksecuritygroupflowevent/**/PT1H.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = false
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Azure_NSG_flow_logs_parse_json]
  type = "remap"
  inputs = ["Azure_NSG_flow_logs_input"]
  source = '''
    ., err = parse_json(.message).records
    if err != null {
      log("Unable to parse JSON: " + err, level: "error")
    }
  '''

[transforms.Azure_NSG_flow_logs_parser_extract_flowTuples]
  type = "remap"
  inputs = ["Azure_NSG_flow_logs_parse_json"]
  source = '''
    extracted_flow = []

    map_values(array!(.properties.flows)) -> |value_root_flow| {
      map_values(array!(value_root_flow.flows)) -> |value_nested_flow| {
        map_values(array!(value_nested_flow.flowTuples)) -> |value_flow_tuple| {
          extracted_flow = push(extracted_flow, value_flow_tuple)
        }
      }
    }

    . = extracted_flow
  '''

[transforms.Azure_NSG_flow_logs_parser_flowTuples_parse_csv_to_sink]
  type = "remap"
  inputs = ["Azure_NSG_flow_logs_parser_extract_flowTuples"]
  source = '''
    flow_fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("Unable to split CSV: " + err, level: "error")
    }

    .timestamp = parse_timestamp!(flow_fields[0], format: "%s")
    .srcaddr = flow_fields[1]
    .dstaddr = flow_fields[2]
    if !is_nullish(flow_fields[3]) {
      .srcport = to_int!(flow_fields[3])
    }
    if !is_nullish(flow_fields[4]) {
      .dstport = to_int!(flow_fields[4])
    }
    .protocol = flow_fields[5]
    .traffic_flow = flow_fields[6]
    .traffic_decision = flow_fields[7]
    .flow_state = flow_fields[8]
    if !is_nullish(flow_fields[9]) {
      .packets_out = to_int!(flow_fields[9])
    }
    if !is_nullish(flow_fields[10]) {
      .bytes_out = to_int!(flow_fields[10])
    }
    if !is_nullish(flow_fields[11]) {
      .packets_in = to_int!(flow_fields[11])
    }
    if !is_nullish(flow_fields[12]) {
      .bytes_in = to_int!(flow_fields[12])
    }

    del(.message)

    .source = "azure_nsg_flow"
    .sourcetype = "azure_artefact"
    .host = "${SOURCE_TENANT:?The source AzureAD tenant is required}"
  '''
