# Description: Process AWS Application Load Balancer access logs.
#              Reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html
#              Filename should match: "*elasticloadbalancing*.log"
#              The exported compressed files can be uncompressed using:
#                find <EXPORT_FOLDER> -type f -iname '*.gz' | xargs -I0 gzip --keep -d 0
#              source = "aws_alb" & sourcetype = "aws_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-12-14
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_TENANT = "<SOURCE_TENANT>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.AWS_Application_Load_Balancer_access_logs_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The source folder containing the Application Load Balancer logs is required}/**/*elasticloadbalancing*.log"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.AWS_Application_Load_Balancer_access_logs_parser]
  type = "remap"
  inputs = ["AWS_Application_Load_Balancer_access_logs_input"]
  source = '''
    ., err = parse_aws_alb_log(.message)
    if (err != null) {
      log("Unable to convert to parse log line: " + err, level: "error")
      abort
    }
  '''

[transforms.AWS_Application_Load_Balancer_access_logs_enrich_to_sink]
  type = "remap"
  inputs = ["AWS_Application_Load_Balancer_access_logs_parser"]
  source = '''
    # Bug with some sink regarding the timestamp, reparsing it.
    .timestamp = parse_timestamp!(.timestamp, format: "%Y-%m-%dT%H:%M:%S.%fZ")

    .host = "${SOURCE_TENANT:?The source AWS tenant / account is required}"
    .source = "aws_alb"
    .sourcetype = "aws_artefact"
  '''
