# Description: Process AWS CloudTrail JSON as exported from a S3 bucket (multiple JSON files with a single Records array each).
#              Filename should match: "*CloudTrail*.json"
#              source = "aws_cloudtrail" & sourcetype = "aws_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-12-14
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_TENANT = "<SOURCE_TENANT>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.AWS_CloudTrail_JSON_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The source folder containing the Insights JSON logs is required}/**/*CloudTrail*.json"]
  # include = ["${INPUT_FOLDER:?The source folder containing the CloudTrail JSON logs is required}/**/*CloudTrail*.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.AWS_CloudTrail_JSON_parser]
  type = "remap"
  inputs = ["AWS_CloudTrail_JSON_input"]
  source = '''
    splitted, err = split(.message, "\n")
    if err != null {
      log("Unable to split message on newlines: " + err, level: "error")
    }

    . = flatten(map_values(splitted) -> |value| {
      parsed_value, err = parse_json(value)
      if err != null {
        log("Unable to parse JSON: " + err, level: "error")
        null
      } else {
        parsed_value.Records
      }
    })
  '''

[transforms.AWS_CloudTrail_JSON_enrich_to_sink]
  type = "remap"
  inputs = ["AWS_CloudTrail_JSON_parser"]
  source = '''
    .timestamp, err = parse_timestamp(.eventTime, format: "%Y-%m-%dT%H:%M:%SZ")
    if err != null {
      log("Unable to convert to timestamp: " + err, level: "error")
    }

    .host = "${SOURCE_TENANT:?The source AWS tenant / account is required}"
    .source = "aws_cloudtrail"
    .sourcetype = "aws_artefact"
  '''
