# Vector_Windows_EZTools_LogParser_SMBServer-Anonymous-Logon config.
# Description: Process Windows SMB anonymous access events parsed with LogParser (CSV output).
#              Filename should match: "*SMBServer-Anonymous-Logon.csv"
#              source = "windows_evtx_smb-anonymous" & sourcetype = "windows_artefact"
#              LogParser command: XXX
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-28
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.LogParser_SMBServer-Anonymous-Logon_csv_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the LogParser SMBServer anonymous logon Events files is required. Add '**' to process the specified folder recursively (example: \"C:\\logs\" or folder \"C:\\logs\\**\")}/**/*SMBServer-Anonymous-Logon.csv"]
  data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.LogParser_SMBServer-Anonymous-Logon_csv_parser]
  type = "remap"
  inputs = ["LogParser_SMBServer-Anonymous-Logon_csv_input"]
  source = '''
    # Expect CSV header:
    # Date,EventID,Description,UserName,ClientName
    fields, err = parse_csv(.message, delimiter: ",")
    if err != null {
      log("[EVTX SMBServer-Anonymous-Logon] Unable to split CSV: " + err, level: "error")
    }

    if fields[1] == "EventID" {
      expected_header = "Date,EventID,Description,UserName,ClientName"
      current_header = strip_whitespace(string!(.message))
      if expected_header != current_header {
        log("Unexpected CSV header, possible non-integrated tool update!\n=> Expected CSV header: " + expected_header + "\n=> Got CSV header:      " + current_header, level: "error")
      }
      abort
    }

    .date = fields[0]
    .eventid = fields[1]
    .description = fields[2]
    .username = fields[3]
    .clientname = fields[4]

    .timestamp = .date

    # Add the metadata fields following the parsing.
    .sourcehost = "${SOURCE_HOST:?The source host is required}"
    .host = .sourcehost
    .source = "windows_evtx_smb-anonymous"
    .sourcetype = "windows_artefact"

    # Delete irrelevant default fields.
    del(.source_type)
    del(.file)
    del(.message)
  '''

[transforms.LogParser_SMBServer-Anonymous-Logon_coerce_to_sink]
  type = "remap"
  inputs = ["LogParser_SMBServer-Anonymous-Logon_csv_parser"]
  source = '''
    . = map_values(.) -> |value| {
      if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_timestamp(value, format: "%Y-%m-%d %H:%M:%S.%f"); err == null) {
        tmp_value
      } else if (tmp_value, err = parse_int(value); err == null) {
        tmp_value
      } else if (tmp_value, err = to_bool(value); err == null) {
        tmp_value
      } else {
        value
      }
    }
  '''
