# Description: Process Azure O365 Unified Audit logs, as retrieved by DFIR-ORC365RC.
#              Filename should match: "**/*UnifiedAuditLog*.json"
# Author(s): Axel ROC, Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   INDEX = "<INDEX>"
#   SOURCE_TENANT = "<SOURCE_TENANT>"
#   -- ELK sink specific variables. ELK index = <INDEX> & source = "o365_unifiedaudit" & sourcetype = "azure_artefact".
#   ELK_IP = "<IP>"
#   ELK_PORT = "<PORT>" -- ELK bulk HTTP API port. Defaults to 9200.
#   ELK_USERNAME = "<USERNAME>"
#   ELK_PASSWORD = "<PASSWORD>"
#   -- Splunk sink specific variables. Splunk index = <INDEX> & source = "o365_unifiedaudit" & sourcetype = "azure_artefact".
#   SPLUNK_IP = "<IP>"
#   SPLUNK_PORT = "<PORT>" -- Splunk HTTP Event Collector port. Defaults to 8088.
#   SPLUNK_HEC_TOKEN = "<SPLUNK_HEC_TOKEN>" -- Splunk HEC token: https://docs.splunk.com/Documentation/Splunk/9.0.1/Data/UsetheHTTPEventCollector.

data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.Azure_O365_UnifiedAuditLog_DFIR-O365RC_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The source folder containing the DFIR-O365RC JSON outputs is required}/**/*UnifiedAuditLog*.json"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Azure_O365_UnifiedAuditLog_DFIR-O365RC_parser]
  inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_input"]
  type = "remap"
  source = '''
  splitted, err = split(.message, "\n")
  if err != null {
    log("Unable to split message on newlines: " + err, level: "error")
  }

  . = map_values(splitted, true) -> |value| {
    is_value_json = value != null && is_json(value)

    if (err == null && is_value_json) {
      parsed_value, err = parse_json(value)
      
      if err != null {
        log("Unable to parse JSON: " + err, level: "error")
        null
      } else {      
        parsed_value
      }
    }
  }
  '''

[transforms.Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich]
  inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_parser"]
  type = "remap"
  source = '''
  if is_null(.CreationTime) == false {
    .CreationTime, err1 = to_timestamp(.CreationTime)
    if err1 != null {
      log("Unable to convert to timestamp: " + err1, level: "error")
    }
  }

  # Fields added to have the same nomenclature between the different log sources (audit, signins, unified logs...)
  .timestamp = .CreationTime
  .AccountName = .UserId

  # Flatten the .DeviceProperties, ExtendedProperties, Parameters, and ModifiedProperties fields.
  # Expected format:
  #   DeviceProperties": [
  #     {
  #       "Name": "OS",
  #       "Value": "MacOs"
  #     },
  #     {
  #       "Name": "BrowserType",
  #       "Value": "Other"
  #     },
  #     [...]
  DevicePropertiesArray = .DeviceProperties
  if is_null(.DeviceProperties) == false {
    DevicePropertiesMapped = {}
    for_each(array!(.DeviceProperties)) -> |_, item| {
      DevicePropertiesMapped = set!(DevicePropertiesMapped, [item.Name], item.Value)
    }
    .DeviceProperties = DevicePropertiesMapped
  }
  
  ExtendedPropertiesArray = .ExtendedProperties
  if is_null(.ExtendedProperties) == false {
    ExtendedPropertiesMapped = {}
    for_each(array!(.ExtendedProperties)) -> |_, item| {
      ExtendedPropertiesMapped = set!(ExtendedPropertiesMapped, [item.Name], item.Value)
    }
    .ExtendedProperties = ExtendedPropertiesMapped
  }

  ParametersArray = .Parameters
  if is_null(.Parameters) == false {
    ParametersMapped = {}
    for_each(array!(.Parameters)) -> |_, item| {
      ParametersMapped = set!(ParametersMapped, [item.Name], item.Value)
    }
    .Parameters = ParametersMapped
  }

  ModifiedPropertiesArray = .ModifiedProperties
  if is_null(.ModifiedProperties) == false {
    ModifiedPropertiesMapped = {}
    for_each(array!(.ModifiedProperties)) -> |_, item| {
      ModifiedPropertiesMapped = set!(ModifiedPropertiesMapped, [item.Name, "OldValue"], item.OldValue)
      ModifiedPropertiesMapped = set!(ModifiedPropertiesMapped, [item.Name, "NewValue"], item.NewValue)
    }
    .ModifiedProperties = ModifiedPropertiesMapped
  }
  
  . = flatten(.)
  # Restore the original fields as well following the flattening, to keep both a flattened and array version.
  .DevicePropertiesArray = DevicePropertiesArray
  .ExtendedPropertiesArray = ExtendedPropertiesArray
  .ParametersArray = ParametersArray
  .ModifiedPropertiesArray = ModifiedPropertiesArray

  .host = "${SOURCE_TENANT:?The source AzureAD tenant is required}"
  .source = "o365_unifiedaudit"
  .sourcetype = "azure_artefact"
  '''

# Sink to send processed logs to void, for validating that the pipeline doest not raise errors.
# [sinks.Azure_O365_UnifiedAuditLog_DFIR-O365RC_sink]
#   type = "blackhole"
#   inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich"]

# Sink to send processed logs to the console, for debugging.
# [sinks.Azure_O365_UnifiedAuditLog_DFIR-O365RC_sink]
#   type = "console"
#   inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich"]
#   target = "stdout"
#   encoding.codec = "json"
  
# Sink transform to send processed logs to an ELK instance.
# [sinks.Azure_O365_UnifiedAuditLog_DFIR-O365RC_ELK_sink]
#   type = "elasticsearch"
#   inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich"]
#   mode="bulk"
#   # bulk.action = "create"
#   bulk.index = "${INDEX:?An index name must be specified for ELK / Splunk index}"
#   endpoint = "http://${ELK_IP:?ELK IP is required}:${ELK_PORT:-9200}"
#   auth.strategy = "basic"
#   auth.user = "${ELK_USERNAME:?ELK_USERNAME is required}"
#   auth.password = "${ELK_PASSWORD:?ELK_PASSWORD is required}"
#   suppress_type_name = true # type field in header is deprecated since ELK 7.x and has been removed from ELK 8.x

# Sink transform to send processed logs to a Splunk instance.
# [sinks.Azure_O365_UnifiedAuditLog_DFIR-O365RC_Splunk_sink]
#   type = "splunk_hec_logs"
#   inputs = ["Azure_O365_UnifiedAuditLog_DFIR-O365RC_enrich"]
#   endpoint = "http://${SPLUNK_IP:?Splunk IP is required}:${SPLUNK_PORT:-8088}"
#   default_token = "${SPLUNK_HEC_TOKEN:?Splunk HEC token is required}"
#   compression = "none"
#   index = "${INDEX:?An index name must be specified for the ELK / Splunk index}"
#   host_key = "host"
#   source = "{{ source }}"
#   sourcetype = "{{ sourcetype }}"
#   tls.verify_certificate = false
#   encoding.codec = "json"