# Description: Process Windows EVTX parsed as JSON with Winlogbeat.
#              Filename should match: "*winlogbeat*"
#              The EVTX can be parsed with Winlogbeat using:
#                - For all events, the Winlogbeat_ALL.mkape KAPE module (https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/Winlogbeat_ALL.mkape)
#                - For a filtered set of events, the Winlogbeat_Windows_EVTX_to_JSON_filtered.yml configuration file in the present repository.
#              source = "windows_evtx" & sourcetype = "windows_artefact"
# Author(s): Thomas DIOT (_Qazeer)
# Version: 1.0
# Last modified: 2022-09-01
# Required environment variables:
#   INPUT_FOLDER = "<INPUT_FOLDER>"
#   VECTOR_TEMP_FOLDER = "<VECTOR_TEMP_FOLDER>"
#   SOURCE_HOST = "<SOURCE_HOST>"

# Temporary folder used by Vector.
data_dir = "${VECTOR_TEMP_FOLDER:?A directory for Vector temporary data is required}"

[sources.Windows_EVTX_winlogbeat_input]
  type = "file"
  include = ["${INPUT_FOLDER:?The input folder containing the Winlogbeat JSON output files is required. Add '**' to process the specified folder recursively (exemple: \"C:\\logs\" or folder \"C:\\logs\\**\")}/*winlogbeat*"]
  ignore_checkpoints = true
  read_from = "beginning"
  oldest_first = true
  fingerprint.strategy = "device_and_inode"
  max_line_bytes = 100_000_000

[transforms.Windows_EVTX_winlogbeat_parser_to_sink]
  type = "remap"
  inputs = ["Windows_EVTX_winlogbeat_input"]
  source = '''
    ., err = parse_json(.message)
    if (err != null) {
      log("Unable to convert to parse log line: " + err, level: "error")
    }

    # Rename / remove fields in the ELK format introduced by Winlogbeat.
    .timestamp = to_timestamp!(.@timestamp)
    del(.@timestamp)
    del(.@metadata)

    # Flatten the Windows event itself from the "winlog" field.
    ., err |= flatten(.winlog)
    del(.winlog)

    # Add the source host following the parsing.
    if !(exists(.computer_name) && .computer_name != "") {
      log("No computer name", level: "error")
    }

    .sourcehost = .computer_name
    .host = .sourcehost
    .source = "windows_evtx"
    .sourcetype = "windows_artefact"
  '''
